name: Integration Test
on:
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at 00:00 UTC

jobs:
  install-and-run-stable-proper7y:
    name: Install and run proper7y (stable version)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Bump Bash version on macOS
        if: matrix.os == 'macos-latest'
        run: |
          bash --version
          brew install bash
          /opt/homebrew/bin/bash --version
      - name: Install and run stable 'proper7y'
        run: |
          make integ-tests

  run-head-proper7y:
    name: Run proper7y (HEAD version)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print working directory
        run: pwd
      - name: ls
        run: ls -alFh
      - name: Bump Bash version on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install bash
          echo "/opt/homebrew/bin" >> "$GITHUB_PATH"
      - name: Verify Bash version on macOS
        if: matrix.os == 'macos-latest'
        run: |
          bash --version
      - name: Run proper7y
        run: ./proper7y
