name: Integration Test
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  install-and-run-stable-property:
    name: Install and run property (stable version)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install and run stable 'property'
        run: |
          make integ-test

  run-head-property:
    name: Run property (HEAD version)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: ls
        run: ls -alFh
      - name: Run property
        run: ./property
