name: Integration Test
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  install-and-run-stable-proper7y:
    name: Install and run proper7y (stable version)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install and run stable 'proper7y'
        run: |
          make integ-tests

  run-head-proper7y:
    name: Run proper7y (HEAD version)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: ls
        run: ls -alFh
      - name: Run proper7y
        run: ./proper7y
