name: Lint
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install devel-tools
        run: make install-devel-tools
      - name: Run lint
        run: make lint
