name: Static Test
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Static Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install devel-tools
        run: make install-devel-tools
      - name: Run static tests
        run: make static-tests
