name: Static Test
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install devel-tools
        run: make install-devel-tools
      - name: Run lint
        run: make lint

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Validate project version consistency
        run: make validate
